# Generated by Django 5.1.3 on 2024-11-10 01:12

import django.db.models.deletion
import src.models.study_plan_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_visibility_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="src.customuser",
                    ),
                ),
                (
                    "visibility",
                    models.ForeignKey(
                        default=src.models.study_plan_model.default_visibility,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="src.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudyPlanTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "study_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="src.studyplan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
