# Generated by Django 5.1.3 on 2024-11-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_studyplan_studyplantopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyplan",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="src.customuser",
            ),
            preserve_default=False,
        ),
    ]
