name: "Angular Build"

defaults:
  run:
    working-directory: frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    
    - name: Setup node ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: npm
        cache-dependency-path: frontend/package-lock.jsonn
    
    - name: Install external dependencies
      run: npm install
    
    - name: Install dependencies
      run: npm ci

    - name: Linting project
      run: npm run lint

    - name: Build
      run: npm run build
