name: "Django Build"

defaults:
  run:
    working-directory: backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pre-commit hooks
      run: |
        source venv/bin/activate
        pre-commit install

    - name: Run pre-commit hooks
      run: |
        source venv/bin/activate
        pre-commit run --all-files
