name: "Django Tests"

defaults:
  run:
    working-directory: backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for missing migrations
      run: |
        source venv/bin/activate
        python3 -m src.manage makemigrations --check --dry-run

    - name: Migrate the database
      run: |
        source venv/bin/activate
        python3 -m src.manage migrate

    - name: Run Django tests
      run: |
        source venv/bin/activate
        python3 -m src.manage test